# Generated by Django 3.2.6 on 2021-11-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_auto_20211117_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
