# Generated by Django 3.2.6 on 2021-11-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='nulo', max_length=30)),
                ('direccion', models.CharField(default='nulo', max_length=50)),
                ('email', models.EmailField(default='nulo', max_length=30, unique=True)),
                ('telefono', models.CharField(default='nulo', max_length=10)),
                ('password', models.CharField(default='nulo', max_length=15)),
            ],
        ),
    ]
