# Generated by Django 3.2.6 on 2021-10-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPededidos', '0004_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
