# Generated by Django 3.2.6 on 2021-11-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPededidos', '0007_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
