# Generated by Django 3.2.6 on 2021-11-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPededidos', '0008_alter_clientes_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulos',
            new_name='Articulo',
        ),
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Pedidos',
        ),
    ]
