# Generated by Django 3.2.6 on 2021-11-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPededidos', '0009_auto_20211114_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(blank=True, default='nulo', max_length=20),
        ),
    ]
