# Generated by Django 3.2.6 on 2021-11-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPededidos', '0010_cliente_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='nulo', max_length=20),
        ),
    ]
